name 'proteon-java'
version '0.1.5'

author 'Sander Bilo'
license 'Apache'
project_page 'http://github.com/Proteon/puppet-java'
source 'git://github.com/Proteon/puppet-java.git'
summary 'Java module'
description 'Puppet code for deploying and configuring Oracle Java on Debian-like servers'
dependency 'puppetlabs/apt', '>=1.1.0'
dependency 'klangrud/profile_d', '>=0.0.1'
