#!/bin/bash

# if 'clients' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: vim

tmux has-session -t clients

if [ $? != 0 ]
then
    # editor window
    tmux new -s clients -n editor -d
    tmux send-keys -t clients:editor 'cd ~/Dropbox/clients' C-m
    tmux send-keys -t clients:editor 'vim .' C-m
    tmux send-keys -t clients:editor ',t' C-m
    tmux send-keys -t clients:editor ':edit ~/Dropbox/clients/worklog.txt' C-m
fi

# select window 'editor'
tmux select-window -t clients:editor

# attach to session
tmux attach -t clients
