#!/bin/bash

# if 'rosetta' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - python: python server.py
# - bash: empty terminal

tmux has-session -t rosetta

if [ $? != 0 ]
then
    # editor window
    tmux new -s rosetta -n editor -d
    tmux send-keys -t rosetta:editor 'cd ~/Projects/Ubiqua/rosetta' C-m
    tmux send-keys -t rosetta:editor 'workon rosetta' C-m
    tmux send-keys -t rosetta:editor 'clear' C-m
    tmux send-keys -t rosetta:editor 'git status' C-m
    tmux send-keys -t rosetta:editor 'vim .'

    # python window
    tmux new-window -t rosetta -n python
    tmux send-keys -t rosetta:python 'cd ~/Projects/Ubiqua/rosetta' C-m
    tmux send-keys -t rosetta:python 'workon rosetta' C-m
    tmux send-keys -t rosetta:python 'clear' C-m
    tmux send-keys -t rosetta:python 'python server.py'

    # bash window
    tmux new-window -t rosetta -n bash
    tmux send-keys -t rosetta:bash 'cd ~/Projects/Ubiqua/rosetta' C-m
    tmux send-keys -t rosetta:bash 'workon rosetta' C-m
    tmux send-keys -t rosetta:bash 'clear' C-m
fi

# select window 'editor'
tmux select-window -t rosetta:editor

# attach to session
tmux attach -t rosetta
