#!/bin/bash

# if 'quanto-api' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - watch: npm start
# - db: database connection

tmux has-session -t quanto-api

if [ $? != 0 ]
then
    # editor window
    tmux new -s quanto-api -n editor -d
    tmux send-keys -t quanto-api:editor 'cd ~/Projects/Quanto/quanto-api' C-m
    tmux send-keys -t quanto-api:editor 'nvm use' C-m
    tmux send-keys -t quanto-api:editor 'clear' C-m
    tmux send-keys -t quanto-api:editor 'git status' C-m
    tmux send-keys -t quanto-api:editor 'vim .'

    # watch window
    tmux new-window -t quanto-api -n watch
    tmux send-keys -t quanto-api:watch 'cd ~/Projects/Quanto/quanto-api' C-m
    tmux send-keys -t quanto-api:watch 'nvm use' C-m
    tmux send-keys -t quanto-api:watch 'clear' C-m
    tmux send-keys -t quanto-api:watch 'npm start'

    # db window
    tmux new-window -t quanto-api -n db
    tmux send-keys -t quanto-api:db 'cd ~/Projects/Quanto/quanto-api' C-m
    tmux send-keys -t quanto-api:db 'nvm use' C-m
    tmux send-keys -t quanto-api:db 'clear' C-m
    tmux send-keys -t quanto-api:db 'ENV=development npm run db:connect' C-m
fi

# select window 'editor'
tmux select-window -t quanto-api:editor

# attach to session
tmux attach -t quanto-api
