#!/bin/bash

# if 'foxv2' session exists, attach to it.
# otherwise, create it with the following windows:
# - fbccontent: vim
# - docker: start docker-compose

tmux has-session -t foxv2

if [ $? != 0 ]
then
    # fbccontent window
    tmux new -s foxv2 -n fbccontent -d
    tmux send-keys -t foxv2:fbccontent 'cd ~/Projects/X-Team/v2/dcgapps' C-m
    tmux send-keys -t foxv2:fbccontent 'nvm use' C-m
    tmux send-keys -t foxv2:fbccontent 'clear' C-m
    tmux send-keys -t foxv2:fbccontent '../update_fox_repos.sh' C-m
    tmux send-keys -t foxv2:fbccontent 'cd fbccontent' C-m
    tmux send-keys -t foxv2:fbccontent 'vim .'

    # docker window
    tmux new-window -t foxv2 -n docker
    tmux send-keys -t foxv2:docker 'cd ~/Projects/X-Team/v2/dcgapps' C-m
    tmux send-keys -t foxv2:docker 'nvm use' C-m
    tmux send-keys -t foxv2:docker 'clear' C-m
    tmux send-keys -t foxv2:docker 'docker-compose up'
fi

# select window 'fbccontent'
tmux select-window -t foxv2:fbccontent

# attach to session
tmux attach -t foxv2
