#!/bin/bash

# if 'foxv3' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - docker: start docker-compose

tmux has-session -t foxv3

if [ $? != 0 ]
then
    # editor window
    tmux new -s foxv3 -n editor -d
    tmux send-keys -t foxv3:editor 'cd ~/Projects/X-Team/brian-hub' C-m
    tmux send-keys -t foxv3:editor 'nvm use' C-m
    tmux send-keys -t foxv3:editor 'clear' C-m
    tmux send-keys -t foxv3:editor '../update_fox_repos.sh' C-m
    tmux send-keys -t foxv3:editor 'vim .' C-m

    # docker window
    tmux new-window -t foxv3 -n docker
    tmux send-keys -t foxv3:docker 'cd ~/Projects/X-Team/brian-hub' C-m
    tmux send-keys -t foxv3:docker 'nvm use' C-m
    tmux send-keys -t foxv3:docker 'clear' C-m
    tmux send-keys -t foxv3:docker 'COMPOSE_HTTP_TIMEOUT=300 docker-compose up'
fi

# select window 'editor'
tmux select-window -t foxv3:editor

# attach to session
tmux attach -t foxv3
