#!/bin/bash

# if 'ave' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - rails: rails console | rails server
# - bash: empty terminal

tmux has-session -t ave

if [ $? != 0 ]
then
    # editor window
    tmux new -s ave -n editor -d
    tmux send-keys -t ave:editor 'cd ~/Projects/Ubiqua/ave' C-m
    tmux send-keys -t ave:editor 'clear' C-m
    tmux send-keys -t ave:editor 'git status' C-m
    tmux send-keys -t ave:editor 'vim .'

    # rails window - console pane
    tmux new-window -t ave -n rails
    tmux send-keys -t ave:rails 'cd ~/Projects/Ubiqua/ave' C-m
    tmux send-keys -t ave:rails 'clear' C-m
    tmux send-keys -t ave:rails 'rails console'

    # rails window - server pane
    tmux split-window -v -t ave:rails
    tmux send-keys -t ave:rails 'cd ~/Projects/Ubiqua/ave' C-m
    tmux send-keys -t ave:rails 'clear' C-m
    tmux send-keys -t ave:rails 'rails server'

    # bash window
    tmux new-window -t ave -n bash
    tmux send-keys -t ave:bash 'cd ~/Projects/Ubiqua/ave' C-m
    tmux send-keys -t ave:bash 'clear' C-m
fi

# select window 'editor'
tmux select-window -t ave:editor

# attach to session
tmux attach -t ave
