#!/bin/bash

# if 'knowledge' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: vim
#   - elasticsearch: elasticsearch learning project

tmux has-session -t knowledge

if [ $? != 0 ]
then
    # editor window
    tmux new -s knowledge -n editor -d
    tmux send-keys -t knowledge:editor 'cd ~/knowledge' C-m
    tmux send-keys -t knowledge:editor 'vim .' C-m
    tmux send-keys -t knowledge:editor ',t' C-m
    tmux send-keys -t knowledge:editor ':edit ~/Dropbox/Learning.md' C-m

    # elasticsearch window
    tmux new-window -t knowledge -n elasticsearch
    tmux send-keys -t knowledge:elasticsearch 'cd ~/Projects/Personales/elasticsearch_learning' C-m
    tmux send-keys -t knowledge:elasticsearch 'docker-compose up -d'
fi

# select window 'editor'
tmux select-window -t knowledge:editor

# attach to session
tmux attach -t knowledge
