#!/bin/bash

# if 'skyroam' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - watch: shopify theme gem watch

tmux has-session -t skyroam

if [ $? != 0 ]
then
    # editor window
    tmux new -s skyroam -n editor -d
    tmux send-keys -t skyroam:editor 'cd ~/Projects/BrandedCrate/Skyroam/custom_template' C-m
    tmux send-keys -t skyroam:editor 'clear' C-m
    tmux send-keys -t skyroam:editor 'git status' C-m
    tmux send-keys -t skyroam:editor 'vim .'

    # watch window
    tmux new-window -t skyroam -n watch
    tmux send-keys -t skyroam:watch 'cd ~/Projects/BrandedCrate/Skyroam/custom_template' C-m
    tmux send-keys -t skyroam:watch 'clear' C-m
    tmux send-keys -t skyroam:watch 'theme watch'
fi

# select window 'editor'
tmux select-window -t skyroam:editor

# attach to session
tmux attach -t skyroam
